### ISSUE TITLE
Sitecore 8 support?

### ISSUE THREAD

**Issue by jst-cyr** [adoprog/Sitecore-Mobile-Device-Detector#18]
I'm working on upgrading a client to Sitecore 8 and they are using this module. I noticed the module is marked as working with 7.5, but not 8, on the marketplace.

Is there a timeline for a Sitecore 8 version?

**Comment by adoprog** [comment]
I haven't checked it but I suppose it should work. 
If you notice any issues - please let me know and I'll fix it :)
